apiVersion: batch/v1
kind: CronJob
metadata:
  name: <name>
spec:
  schedule: "*/5 * * * *"  # Cron schedule (every 5 minutes)
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: my-app  # Labels for the cron job pods
        spec:
          containers:
          - name: my-container
            image: busybox
            command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 30"]
          restartPolicy: OnFailure  # Restart policy for the cron job pods
